---
- name: Converge
  hosts: all
  collections:
   - matthewcosgrove.tools_vm
  tasks:
    - name: "Include bucc_tools"
      include_role:
        name: "bucc_tools"
    - name: "Include vim"
      include_role:
        name: "vim"
    - name: "Include ubuntu_user"
      include_role:
        name: "ubuntu_user"
